### ISSUE TITLE
Adding this plugin causes test to crash

### ISSUE THREAD

**Issue by Graham42** [cypress-io/cypress-watch-preprocessor#1]
- Operating System: Ubuntu 16.04
- Cypress Version: 1.1.3
- Cypress watch plugin version: 1.0.0
- Browser Version: Chrome 62

### Is this a Feature or Bug?
Bug

### Current behavior:
Added this plugin as per instructions in the readme and my test crashes before even starting. 
No other changes were made. Confirmed by removing the plugin, and the test worked, re-added plugin, test crashed.

Error Stack:
<details>

```
Uncaught SyntaxError: Unexpected token import
This error originated from *your* test code, not from Cypress.
When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
Cypress could not associate this error to any specific test.
We dynamically generated a new test to display this failure.
Check your console for the stack trace or click this message to see where it originated from.

logError                                @ cypress_runner.js:136650
(anonymous)                             @ cypress_runner.js:136324
EventEmitter.emit                       @ cypress_runner.js:105543
(anonymous)                             @ cypress_runner.js:101214
EventEmitter.emit                       @ cypress_runner.js:105543
emit                                    @ cypress_runner.js:101249
Test._this._onErrorClick                @ cypress_runner.js:103275
(anonymous)                             @ cypress_runner.js:101388
executeAction                           @ cypress_runner.js:124960
res                                     @ cypress_runner.js:124951
boundFunc                               @ cypress_runner.js:90009
ReactErrorUtils.invokeGuardedCallback   @ cypress_runner.js:90015
executeDispatch                         @ cypress_runner.js:84179
executeDispatchesInOrder                @ cypress_runner.js:84199
executeDispatchesAndRelease             @ cypress_runner.js:83614
executeDispatchesAndReleaseTopLevel     @ cypress_runner.js:83625
forEachAccumulated                      @ cypress_runner.js:95261
processEventQueue                       @ cypress_runner.js:83825
runEventQueueInBatch                    @ cypress_runner.js:90037
handleTopLevel                          @ cypress_runner.js:90047
handleTopLevelImpl                      @ cypress_runner.js:90122
perform                                 @ cypress_runner.js:94585
batchedUpdates                          @ cypress_runner.js:89810
batchedUpdates                          @ cypress_runner.js:92751
dispatchEvent                           @ cypress_runner.js:90197


```

</details>

### Desired behavior:
Don't crash.

### How to reproduce:

Follow steps from readme:
1. `npm install --save-dev @cypress/watch-preprocessor`
2. Edit the cypress `plugins/index.js` file to look like this:
  ```
const watch = require('@cypress/watch-preprocessor');

module.exports = (on, config) => {
  on('file:preprocessor', watch());
};
```

**Comment by brian-mann** [comment]
@chrisbreiding can you comment on this? I think this was a simple example of a preprocessor just watching files. I'm assuming you're writing test syntax that the browser cannot understand without the transpilation step - which this preprocessor is omitting.

Now that I think about it, why are we even suggesting this preprocessor at all? @Graham42 were you trying it out to learn about how to build a preprocessor - or did you pick this because you thought it was going to add in some feature / functionality you thought you needed?

Reason I ask is that this was really supposed to be a simple example / demonstration and not really for end user use.

**Comment by chrisbreiding** [comment]
I'm also curious why @Graham42 is looking to use this as well. 

It's not necessarily just an example. It has a legitimate use-case, but with the understanding that your spec files do not get transpiled at all, so your browser must support any JavaScript features you use. 

In this case, @Graham42, it looks like you're using `import`, but that's not supported by Chrome yet. I'd suggest you use the default preprocessor or the [webpack preprocessor](https://github.com/cypress-io/cypress-webpack-preprocessor) and it will transpile and bundle the code so you can use the latest JavaScript features.

I'm closing this since it's not actually a bug, but please let us know what your expectations were for this preprocessor so we can perhaps update the readme to be clearer.

**Comment by Graham42** [comment]
Thanks @chrisbreiding for clarifying. I now understand that by using this I was bypassing the default babel transpiling that allows `import`.

My thought was I might be able to use this, or some variation, to watch files other that the test files.

**Comment by chrisbreiding** [comment]
I see. I think it would be possible to write a preprocessor plugin or modify one of the existing ones to achieve that. It would be a matter of watching the non-test files you're interested in and utilizing the [file object](https://docs.cypress.io/api/plugins/preprocessors-api.html#File-object) provided by the preprocessor API to `emit('rerun')`. It would be a bit of a hack, but it could work.

Watching non-test files is on our radar, so we'll eventually have a first-class solution for it. You can track any progress via https://github.com/cypress-io/cypress/issues/456. https://github.com/cypress-io/cypress/issues/412 has some more context too.
